### ISSUE TITLE
VL-PET: Vision-and-Language Parameter-Efficient Tuning via Granularity Control

### ISSUE THREAD

**Issue by HenryHZY** [jianghaojun/Awesome-Parameter-Efficient-Transfer-Learning#5]
Hi @jianghaojun , you might be interested in our ICCV'23 paper.
paper: https://arxiv.org/abs/2308.09804
code: https://github.com/HenryHZY/VL-PET
project page: https://henryhzy.github.io/VL-PET
baselines: LoRA, VL-Adapter, LST and etc.

**Comment by jianghaojun** [comment]
Added
